apiVersion: apps/v1
kind: Deployment
metadata:
  name: suwayomi
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: suwayomi

  template:
    metadata:
      labels:
        app: suwayomi
        policy-type: "app"

    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

      containers:
        - name: suwayomi
          image: ghcr.io/suwayomi/tachidesk:latest

          securityContext:
              allowPrivilegeEscalation: false

          env:
            - name: TZ
              value: "America/Los_Angeles"
            - name: BIND_IP
              value: "0.0.0.0"
            - name: BIND_PORT
              value: "4567"

          ports:
            - containerPort: 4567
              protocol: TCP

          volumeMounts:
            - name: suwayomi-data
              mountPath: /home/suwayomi/.local/share/Tachidesk
            - name: suwayomi-manga
              mountPath: /downloads/manga
            - name: suwayomi-comics
              mountPath: /downloads/comics

      restartPolicy: Always

      volumes:
        - name: suwayomi-data
          persistentVolumeClaim:
            claimName: suwayomi-config-pvc-nfs
        - name: suwayomi-manga
          persistentVolumeClaim:
            claimName: suwayomi-manga-pvc-nfs
        - name: suwayomi-comics
          persistentVolumeClaim:
            claimName: suwayomi-comics-pvc-nfs
