apiVersion: v1
kind: Service
metadata:
  name: suwayomi
  labels:
    app: suwayomi
    app.kubernetes.io/name: suwayomi
    app.kubernetes.io/instance: suwayomi
    app.kubernetes.io/component: web
spec:
  selector:
    app: suwayomi
  type: ClusterIP
  ports:
    - port: 4567
      targetPort: 4567
      protocol: TCP
