---
# Kavita HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kavita-route
  namespace: kavita
  annotations:
    external-dns.alpha.kubernetes.io/hostname: kavita.seyzahl.com
spec:
  parentRefs:
    - name: kavita-gateway
      sectionName: http
  hostnames:
    - kavita.seyzahl.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: kavita
          port: 5000
          weight: 100
