apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium
  - external-secrets
  - external-dns
  - local-path
  - renovate
  - csi-driver
  - csi-driver-iscsi
  - gateway-api
  - cert-manager
  # - newt
  # - kmcp
