[env]
OMNICONFIG = "{{config_root}}/omniconfig.yaml"
TALOSCONFIG = "{{config_root}}/talosconfig.yaml"

[tools]
k9s = "latest"
kubelogin = "latest"
talosctl = "latest"
kubectl = "latest"
flux2 = "latest"
helm = "latest"
