apiVersion: v1
kind: ConfigMap
metadata:
  name: postiz-configmap
data:
  # URLs
  MAIN_URL: "https://postiz.seyzahl.com"
  FRONTEND_URL: "https://postiz.seyzahl.com"
  NEXT_PUBLIC_BACKEND_URL: "https://postiz.seyzahl.com/api"
  BACKEND_INTERNAL_URL: "http://localhost:3000"

  # Redis
  REDIS_URL: "redis://postiz-redis.postiz.svc.cluster.local:6379"

  # Temporal
  TEMPORAL_ADDRESS: "postiz-temporal.postiz.svc.cluster.local:7233"

  # Storage
  STORAGE_PROVIDER: "local"
  UPLOAD_DIRECTORY: "/uploads"
  NEXT_PUBLIC_UPLOAD_DIRECTORY: "/uploads"

  # Settings
  IS_GENERAL: "true"
  DISABLE_REGISTRATION: "true"
