apiVersion: v1
kind: Service
metadata:
  name: homehub
  labels:
    app: homehub
    app.kubernetes.io/name: homehub
    app.kubernetes.io/instance: homehub
    app.kubernetes.io/component: web
spec:
  selector:
    app: homehub
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
