apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flux-github-token
  namespace: flux-system
spec:
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    name: flux-github-token
    template:
      data:
        username: git
        password: "{{ .token }}"
  data:
    - secretKey: token
      remoteRef:
        key: flux-github-token
