apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system-push
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/pedrotchang/homelab
  ref:
    branch: main
  secretRef:
    name: flux-github-token
