apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: blog
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: blog
  filterTags:
    # Match build-YYYYMMDDHHMMSS format
    pattern: '^build-(?P<ts>[0-9]+)$'
    extract: '$ts'
  policy:
    numerical:
      order: asc
