apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github-token-secret.yaml
  - gitrepository-push.yaml
  - imagerepository.yaml
  - imagepolicy.yaml
  - imageupdateautomation.yaml
