apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-configmap
data:
  EULA: "TRUE"
  TYPE: "CURSEFORGE"
  CF_SLUG: "all-the-mods-10"
  CF_FILENAME_MATCHER: "Server"
  MEMORY: "4G"
  CF_OVERRIDES_EXCLUSIONS: |
    shaderpacks/**
  CF_EXCLUDE_MODS: "colorwheel"
  CF_FORCE_SYNCHRONIZE: "TRUE"
  REMOVE_OLD_MODS: "TRUE"
  ALLOW_FLIGHT: "TRUE"
  OVERRIDE_SERVER_PROPERTIES: "false"
  SEED: "7783552872028868482"
  OPS: |
    a_seyza
  MAX_PLAYERS: "5"
  ENABLE_RCON: "true"
