apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-seyzahl-cert
  namespace: default
spec:
  secretName: wildcard-seyzahl-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - "*.seyzahl.com"
    - "seyzahl.com"
    - "*.local.seyzahl.com"
