apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless-ngx
resources:
  - namespace.yaml
  - deployment.yaml
  - paperless-gpt.yaml
  - redis.yaml
  - gotenberg.yaml
  - tika.yaml
  - service.yaml
  - secrets.yaml
  - storage.yaml
