apiVersion: v1
kind: Service
metadata:
  name: n8n
  labels:
    app: n8n
    app.kubernetes.io/name: n8n
    app.kubernetes.io/instance: n8n
    app.kubernetes.io/component: automation
  annotations:
    omni-kube-service-exposer.sidero.dev/label: n8n
    omni-kube-service-exposer.sidero.dev/port: "3008"
  namespace: n8n
spec:
  selector:
    app: n8n
  type: ClusterIP
  ports:
    - port: 3008
