apiVersion: v1
kind: Service
metadata:
  name: n8n
  annotations:
    omni-kube-service-exposer.sidero.dev/label: n8n
    omni-kube-service-exposer.sidero.dev/port: "3008"
  namespace: n8n
spec:
  selector:
    app: n8n
  type: ClusterIP
  ports:
    - port: 3008
