apiVersion: v1
kind: Service
metadata:
  name: garden
  namespace: garden
  labels:
    app: garden
    app.kubernetes.io/name: garden
    app.kubernetes.io/instance: garden
    app.kubernetes.io/component: web
spec:
  selector:
    app: garden
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  type: ClusterIP
