apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-configmap
data:
  DB_POSTGRESDB_DATABASE: "n8n"
  DB_POSTGRESDB_HOST: "n8n-pg.seyzahl.com"
  DB_POSTGRESDB_PORT: "5432"
  DB_TYPE: "postgresdb"
  N8N_DIAGNOSTICS_ENABLED: "false"
  N8N_HOST: "auto.seyzahl.com"
  N8N_PERSONALIZATION_ENABLED: "false"
  N8N_PORT: "3008"
  N8N_PROTOCOL: "https"
  N8N_SECURE_COOKIE: "false"
  N8N_VERSION_NOTIFICATIONS_ENABLED: "false"
  WEBHOOK_URL: "https://auto.seyzahl.com/"
  N8N_SECURE_COOKIE: "true"
  GENERIC_TIMEZONE: "America/Los_Angeles"
