newtInstances:
  - name: "main-tunnel"
    enabled: true
    auth:
      existingSecretName: "newt-auth-keys"
      keys:
        endpointKey: "endpoint-key"
        idKey: "id-key"
        secretKey: "secret-key"
