apiVersion: v1
kind: Service
metadata:
  name: lux-api
  labels:
    app: lux-api
    app.kubernetes.io/name: lux-api
    app.kubernetes.io/instance: lux-api
    app.kubernetes.io/component: ai
spec:
  selector:
    app: lux-api
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
