apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik
  - blog
  - commafeed
  - garden
  - homehub
  - homepage
  - immich
  - linkding
  - n8n
  - ollama
  - pgadmin
  - wallabag
  # - minecraft
  # - kagent
  # - n8n-mcp
