apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik
  - blog
  - commafeed
  - forgejo
  - forgejo-runner
  - garden
  - homepage
  - immich
  - linkding
  # - lux-api
  - n8n
  - ollama
  - open-webui
  # - pai-memory
  - paperless-ngx
  - pgadmin
  - postiz
  - wallabag
  - workspace-mcp
  # - minecraft
  # - kagent
  # - n8n-mcp
