apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik
  - blog
  - commafeed
  - forgejo
  - forgejo-runner
  - garden
  - homepage
  - immich
  - linkding
  - n8n
  # - ollama
  # - pai-memory
  - pgadmin
  - wallabag
  # - minecraft
  # - kagent
  # - n8n-mcp
