apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - homepage
  - linkding
  - n8n
  - wallabag
  - commafeed
  - suwayomi
  - immich
  - kagent
  - n8n-mcp
  - blog
  - authentik
  # - minecraft
