apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-configmap
data:
  # pgAdmin server mode config
  PGADMIN_CONFIG_SERVER_MODE: "True"
  PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
  PGADMIN_LISTEN_PORT: "80"
  # Auto-load servers from JSON file
  PGADMIN_SERVER_JSON_FILE: "/pgadmin4/servers.json"
