apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-servers
  namespace: pgadmin
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "Linkding",
          "Group": "Homelab Databases",
          "Host": "linkding-pg.seyzahl.com",
          "Port": 5432,
          "MaintenanceDB": "linkding",
          "Username": "linkding",
          "SSLMode": "prefer",
          "PassFile": "/pgadmin4/pgpass"
        },
        "2": {
          "Name": "N8N",
          "Group": "Homelab Databases",
          "Host": "n8n-pg.seyzahl.com",
          "Port": 5432,
          "MaintenanceDB": "n8n",
          "Username": "n8n",
          "SSLMode": "prefer",
          "PassFile": "/pgadmin4/pgpass"
        },
        "3": {
          "Name": "Wallabag",
          "Group": "Homelab Databases",
          "Host": "wallabag-pg.seyzahl.com",
          "Port": 5432,
          "MaintenanceDB": "wallabag",
          "Username": "wallabag",
          "SSLMode": "prefer",
          "PassFile": "/pgadmin4/pgpass"
        },
        "4": {
          "Name": "Commafeed",
          "Group": "Homelab Databases",
          "Host": "commafeed-pg.seyzahl.com",
          "Port": 5432,
          "MaintenanceDB": "commafeed",
          "Username": "commafeed",
          "SSLMode": "prefer",
          "PassFile": "/pgadmin4/pgpass"
        },
        "5": {
          "Name": "Immich",
          "Group": "Homelab Databases",
          "Host": "immich-pg.seyzahl.com",
          "Port": 5432,
          "MaintenanceDB": "immich",
          "Username": "immich",
          "SSLMode": "prefer",
          "PassFile": "/pgadmin4/pgpass"
        },
        "6": {
          "Name": "Authentik",
          "Group": "Homelab Databases",
          "Host": "authentik-pg.seyzahl.com",
          "Port": 5432,
          "MaintenanceDB": "authentik",
          "Username": "authentik",
          "SSLMode": "prefer",
          "PassFile": "/pgadmin4/pgpass"
        },
        "7": {
          "Name": "pgAdmin Config",
          "Group": "Homelab Databases",
          "Host": "pgadmin-pg.seyzahl.com",
          "Port": 5432,
          "MaintenanceDB": "pgadmin",
          "Username": "pgadmin",
          "SSLMode": "prefer",
          "PassFile": "/pgadmin4/pgpass"
        }
      }
    }
