apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-ngx-configmap
data:
  # Database
  PAPERLESS_DBHOST: "paperless-pg.seyzahl.com"
  PAPERLESS_DBPORT: "5432"
  PAPERLESS_DBNAME: "paperless"

  # Redis
  PAPERLESS_REDIS: "redis://paperless-redis:6379"

  # Tika and Gotenberg
  PAPERLESS_TIKA_ENABLED: "true"
  PAPERLESS_TIKA_ENDPOINT: "http://paperless-tika:9998"
  PAPERLESS_TIKA_GOTENBERG_ENDPOINT: "http://paperless-gotenberg:3000"

  # App config
  PAPERLESS_URL: "https://paperless.seyzahl.com"
  PAPERLESS_TIME_ZONE: "America/Los_Angeles"
  PAPERLESS_OCR_LANGUAGE: "eng"
  PAPERLESS_TASK_WORKERS: "2"
  PAPERLESS_THREADS_PER_WORKER: "2"

  # Disable first-time wizard since admin is auto-created
  PAPERLESS_ADMIN_MAIL: ""
